version: '3.9'

services:
  grpc-backend:
    image: erpya/adempiere-grpc-server:master
    container_name: adempiere-backend
    stdin_open: true
    tty: true
    environment:
      - SERVER_PORT=50059
      - SERVICES_ENABLED=access; business; core; dashboarding; dictionary; enrollment; log; ui; workflow; store; pos; updater;
      - SERVER_LOG_LEVEL=WARNING
      # Consider the host and network where the docker server is located
      - DB_HOST=postgres_host
      - DB_PORT=5432
      - DB_NAME=adempiere
      - DB_USER=adempiere
      - DB_PASSWORD=adempiere
      - DB_TYPE=PostgreSQL
    ports:
      - 50059:50059

  redis:
    image: redis:4-alpine
    container_name: adempiere-redis
    stdin_open: true
    tty: true
    ports:
      - '6379:6379'

  es7:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: adempiere-eslastic-search
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xmx512m -Xms512m

  api-rest:
    image: erpya/proxy-adempiere-api:master
    container_name: adempiere-proxy
    depends_on:
      - es7
      - redis
    stdin_open: true
    tty: true
    environment:
      - SERVER_PORT=8085
      - AD_DEFAULT_HOST=adempiere-backend
      - AD_DEFAULT_PORT=50059
      - AD_TOKEN="adempiere_token"
      - AD_STORE_TOKEN="adempiere_store_token"
      - ES_HOST=adempiere-eslastic-search
      - ES_PORT=9200
      - INDEX=vue_storefront_catalog
      - RESTORE_DB=N
      - REDIS_HOST=adempiere-redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    ports:
      - 8085:8085

  vue-app:
    image: erpya/adempiere-vue:develop
    container_name: adempiere-frontend
    depends_on:
      - api-rest
      - grpc-backend
    stdin_open: true
    tty: true
    environment:
      # Set the ip or dns of the server (not the dns of the container) to access from other client hosts
      - API_URL=http://localhost:8085
    ports:
      - 9526:80

  e-commerce:
    image: erpya/adempiere-ecommerce
    container_name: adempiere-ecommerce
    depends_on:
      - api-rest
      - grpc-backend
    stdin_open: true
    tty: true
    environment:
      - SERVER_PORT=3000
      # Set the ip or dns of the server (not the dns of the container) to access from other client hosts
      - API_URL=http://localhost:8085
      - STORE_INDEX=vue_storefront_catalog
      - VS_ENV=dev
    ports:
      - 3000:3000
